/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MedicationSafetyOfficerWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Medication.Drug;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DrugIssueRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class CustomerDrugResponseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerDrugResponseJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private DrugIssueRequest drugIssueRequest;
    private EcoSystem ecoSystem;
    public CustomerDrugResponseJPanel(JPanel upc, UserAccount ua, Enterprise ep, EcoSystem es) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.userAccount = ua;
        this.enterprise = ep;
        this.ecoSystem = es;
        populateDrugComboBox();
    }

    private void populateDrugComboBox(){
        drugComboBox.removeAllItems();
        for(Drug drug:ecoSystem.getDrugCatalog().getDrugCatalog()){
            if(drug.getStatus() == null){
                return;
            }
            if(drug.getStatus().equals("Approved")){
                if (drug.getPharmaceuticalId() == enterprise.getEnterpriseId()) {
                    drugComboBox.addItem(drug);
                }
            }
        }
    }
    
    private void populateDrugIssueTable(Drug drug){
        DefaultTableModel model = (DefaultTableModel) issuesTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest workRequest:drug.getWorkQueue().getWorkRequestList()){
            if(workRequest instanceof DrugIssueRequest){
             drugIssueRequest = (DrugIssueRequest)workRequest;
             Object[] row = new Object[7];
             row[0] = drugIssueRequest.getRequestID();
             row[1] = drug;
             row[2] = drugIssueRequest.getDrugSafetyIssue();
             row[3] = drugIssueRequest.getSender() == null? ("N/A") : drugIssueRequest.getSender().getPerson().getName();
            // row[4] = drugIssueRequest.getOrganizationName();
             row[4] = drugIssueRequest;
             row[5] = drugIssueRequest.getCallBackRequest();
             row[6] = drugIssueRequest.getRdate();
             model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drugComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        issuesTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        drugOkBtn = new javax.swing.JButton();
        callBackBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Customer Drug Response Panel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Drug :");

        drugComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drugComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugComboBoxActionPerformed(evt);
            }
        });

        issuesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Medicine ", "Safety Issues", "Sender", "Status", "Callback", "Timestamp"
            }
        ));
        jScrollPane1.setViewportView(issuesTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText(">> Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        drugOkBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        drugOkBtn.setText("Is Drug Safe?");
        drugOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugOkBtnActionPerformed(evt);
            }
        });

        callBackBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        callBackBtn.setText("Call Back");
        callBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(drugComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refreshBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(562, 562, 562)
                        .addComponent(drugOkBtn)
                        .addGap(94, 94, 94)
                        .addComponent(callBackBtn)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(drugComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(refreshBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugOkBtn)
                    .addComponent(callBackBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void callBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callBackBtnActionPerformed
        int selectedRow = issuesTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first!");
            return;
        }
        DrugIssueRequest dRequest = (DrugIssueRequest)issuesTable.getValueAt(selectedRow, 4);
        Drug drug = (Drug) issuesTable.getValueAt(selectedRow,1);
        if((dRequest.getCallBackRequest().equals("Yes"))){
            JOptionPane.showMessageDialog(null, "Drug already removed from the market!");
            return;
       }else{
            dRequest.setCallBackRequest("Yes");
            dRequest.setStatus("Drug Withdrawn");
            
            for(Drug drug1:ecoSystem.getDrugCatalog().getDrugCatalog()){
                if(drug1.getDrugId() == drug.getDrugId()){
                    drug1.setStatus("Drug Disapproved");
                }
            }
            for (Drug drug2 : enterprise.getDrugCatalog().getDrugCatalog()) {
                if (drug2.getDrugId() == drug.getDrugId()) {
                    drug2.setStatus("Drug Disapproved");
                }
            }
        }
        populateDrugComboBox();
        Drug d = (Drug) drugComboBox.getSelectedItem();
        populateDrugIssueTable(d);
    }//GEN-LAST:event_callBackBtnActionPerformed

    private void drugOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugOkBtnActionPerformed
        int selectedRow = issuesTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first!");
            return;
        }
        
        DrugIssueRequest dRequest = (DrugIssueRequest)issuesTable.getValueAt(selectedRow, 4);
        Drug drug = (Drug) issuesTable.getValueAt(selectedRow,1);
        
        if(dRequest.getStatus().equals("Drug Success")){
           JOptionPane.showMessageDialog(null, "Respond alredy sent as SUCCESS!");
           return;
       }
        
        if(dRequest.getCallBackRequest().equals("Yes")){
           JOptionPane.showMessageDialog(null, "Drug has already been called back");
           return; 
       }
        
        dRequest.setStatus("Drug Success");
        dRequest.setCallBackRequest("No");
        populateDrugIssueTable(drug);
    }//GEN-LAST:event_drugOkBtnActionPerformed

    private void drugComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugComboBoxActionPerformed
        Drug drug = (Drug) drugComboBox.getSelectedItem();
        if (drug != null) {
            populateDrugIssueTable(drug);
        }
    }//GEN-LAST:event_drugComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        Drug drug = (Drug) drugComboBox.getSelectedItem();
        if (drug != null) {
            populateDrugIssueTable(drug);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton callBackBtn;
    private javax.swing.JComboBox drugComboBox;
    private javax.swing.JButton drugOkBtn;
    private javax.swing.JTable issuesTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
