/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmaceuticalAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.HealthIssues.Disease;
import Business.Medication.Drug;
import Business.WorkQueue.DrugApprovalRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class CreateMedicineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMedicineJPanel
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    
    public CreateMedicineJPanel(JPanel upc, Enterprise ep,EcoSystem es) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.ecoSystem = es;
        this.enterprise = ep;
        populateDiseaseComboBox();
        populatePerscriptionComboBox();
    }

    private void populateDiseaseComboBox(){
        diseaseComboBox.removeAllItems();
        diseaseComboBox.addItem(Disease.Asthma);
        diseaseComboBox.addItem(Disease.Cancer);
        diseaseComboBox.addItem(Disease.Cholera);
        diseaseComboBox.addItem(Disease.Diabetes);
        diseaseComboBox.addItem(Disease.Leprosy);
        diseaseComboBox.addItem(Disease.Other);
    }
    
    private void populatePerscriptionComboBox(){
        perscriptionComboBox.removeAllItems();
        perscriptionComboBox.addItem(Drug.Yes);
        perscriptionComboBox.addItem(Drug.No);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        medCodeTxt = new javax.swing.JTextField();
        usesTxt = new javax.swing.JTextField();
        sideEffectsTxt = new javax.swing.JTextField();
        diseaseComboBox = new javax.swing.JComboBox();
        medNameTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        listPriceTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        expiryDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        perscriptionComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Create Medicine Panel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Medicine Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Medicine Code");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Purpose/ Cure Disease ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Usage: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Side Effects / Risks :");

        medCodeTxt.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N

        usesTxt.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        usesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usesTxtActionPerformed(evt);
            }
        });

        sideEffectsTxt.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N

        diseaseComboBox.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        diseaseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseaseComboBoxActionPerformed(evt);
            }
        });

        medNameTxt.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backBtn.setText(">> Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        createBtn.setBackground(new java.awt.Color(255, 153, 153));
        createBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel7.setText("List Price");

        listPriceTxt.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel8.setText("Expiry Date ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel9.setText("Perscription Required ");

        perscriptionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(expiryDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(listPriceTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medCodeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(perscriptionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usesTxt)
                                    .addComponent(sideEffectsTxt)
                                    .addComponent(diseaseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(414, 414, 414))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(medNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(medCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(listPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(expiryDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(perscriptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diseaseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sideEffectsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(createBtn)
                .addGap(26, 26, 26)
                .addComponent(backBtn)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usesTxtActionPerformed

    private void diseaseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseaseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseaseComboBoxActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        String medName = medNameTxt.getText().trim();
        String medCode = medCodeTxt.getText().trim();
        String purpose = (String) diseaseComboBox.getSelectedItem();
        String ipr = (String) perscriptionComboBox.getSelectedItem();
        Boolean finalIPR = Boolean.parseBoolean(ipr);
        
        String usage = usesTxt.getText().trim();
        String sideEffects = sideEffectsTxt.getText().trim();
        String pharmaName = enterprise.getName();
        int pharmaId = enterprise.getEnterpriseId();
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");
       
        Date date1 = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-mm-dd");
        Date dateSelector = expiryDateChooser.getDate();
        
        if(dateSelector == null){
            JOptionPane.showMessageDialog(null, "Please select expiry Date for the Medicine!");
            expiryDateChooser.setBackground(Color.red);
            return;
        }
        
        if(date1.compareTo(dateSelector) > 0){
            JOptionPane.showMessageDialog(null, "Date should be greater than the current date");
            expiryDateChooser.setBackground(Color.red);
            return;
        }
        String expiryDate = DateFormat.getDateInstance().format(dateSelector);
        
        int listPrice=0;
        try{
            listPrice=Integer.parseInt(listPriceTxt.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Invalid Format for List price!");
            return;
        }
        
        if(listPrice<=0){
            JOptionPane.showMessageDialog(null,"Price cannot be negative!");
            return;
        }
        
        if (medName.equals("") || medName.equals(null)||medCode.equals("") || medCode.equals(null)||purpose.equals("") || usage.equals("") || sideEffects.equals("")||
            listPrice == 0) {
            JOptionPane.showMessageDialog(null, "All Fields are mandatory, Please fill all the details!");
            return;
        }
        
        Drug drug = enterprise.getDrugCatalog().addDrugs(medName, medCode, sideEffects, listPrice, expiryDate, finalIPR, usage, purpose, pharmaName, pharmaId);
        // ecoSystem.getDrugCatalog().getDrugCatalog().add(drug);
        JOptionPane.showMessageDialog(null, "Medicine Created!");
        DrugApprovalRequest drugRequest = new DrugApprovalRequest();
        drugRequest.setStatus("N/A");
        drugRequest.setePriseId(enterprise.getEnterpriseId());
        drugRequest.setePriseName(enterprise.getName());
        drugRequest.getDrugCatalog().getDrugCatalog().add(drug);
        drugRequest.setMessage("Evaluation Required");
        enterprise.getWorkQueue().getWorkRequestList().add(drugRequest);
        resetFields();
    }//GEN-LAST:event_createBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed
    
    private void resetFields(){
        medNameTxt.setText("");
        medCodeTxt.setText("");
        sideEffectsTxt.setText("");
        usesTxt.setText("");
        listPriceTxt.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JComboBox diseaseComboBox;
    private com.toedter.calendar.JDateChooser expiryDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField listPriceTxt;
    private javax.swing.JTextField medCodeTxt;
    private javax.swing.JTextField medNameTxt;
    private javax.swing.JComboBox perscriptionComboBox;
    private javax.swing.JTextField sideEffectsTxt;
    private javax.swing.JTextField usesTxt;
    // End of variables declaration//GEN-END:variables
}
