/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HealthOfficialAuthorityWorkArea;

import Business.EcoSystem;
import Business.HealthOfficialAuthority.HOAuthority;
import Business.Medication.Drug;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DrugIssueRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class CustomerMedicationIssuesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerMedicationIssuesJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private HOAuthority authority;
    private UserAccount userAccount;
    private DrugIssueRequest drugIssueRequest;
    
    public CustomerMedicationIssuesJPanel(JPanel upc, HOAuthority au, UserAccount ua, EcoSystem es) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.userAccount = ua;
        this.authority = au;
        this.ecoSystem = es;
        populateDrugComboBox();
        
    }
    
    private void populateDrugComboBox(){
        drugComboBox.removeAllItems();
        for(Drug drug:ecoSystem.getDrugCatalog().getDrugCatalog()){
            if(drug.getStatus() == null){
            }
            if(drug.getStatus().equals("Approved")){
                drugComboBox.addItem(drug);
            }
        }
    }
    
    private void populateDrugIssueTable(Drug drug){
        DefaultTableModel model = (DefaultTableModel) issuesTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest workRequest:drug.getWorkQueue().getWorkRequestList()){
            if(workRequest instanceof DrugIssueRequest){
             drugIssueRequest = (DrugIssueRequest)workRequest;
             Object[] row = new Object[8];
             row[0] = drugIssueRequest.getRequestID();
             row[1] = drug;
             row[2] = drugIssueRequest.getDrugSafetyIssue();
             row[3] = drugIssueRequest.getSender() == null? ("N/A") : drugIssueRequest.getSender().getPerson().getName();
             row[4] = drugIssueRequest.getePriseName();
             row[5] = drugIssueRequest;
             row[6] = drugIssueRequest.getCallBackRequest();
             row[7] = drugIssueRequest.getRdate();
             model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drugComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        issuesTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        callBackBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Medication Issues Panel");

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel2.setText("Drug :");

        drugComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drugComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugComboBoxActionPerformed(evt);
            }
        });

        issuesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Medicine ", "Safety Issues", "Sender", "Organization", "Status", "Callback", "Timestamp"
            }
        ));
        jScrollPane1.setViewportView(issuesTable);

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        backBtn.setText(">> Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        callBackBtn.setBackground(new java.awt.Color(255, 153, 153));
        callBackBtn.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        callBackBtn.setText("Call Back");
        callBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callBackBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(255, 153, 153));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(428, 428, 428)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel2)
                                .addGap(87, 87, 87)
                                .addComponent(drugComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(backBtn)))
                        .addGap(0, 512, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(callBackBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(drugComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(refreshBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(callBackBtn)
                .addGap(244, 244, 244)
                .addComponent(backBtn)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drugComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugComboBoxActionPerformed
        Drug drug = (Drug) drugComboBox.getSelectedItem();
        if (drug != null) {
            populateDrugIssueTable(drug);
        }
    }//GEN-LAST:event_drugComboBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void callBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callBackBtnActionPerformed
        int selectedRow = issuesTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first!");
            return;
        }
        DrugIssueRequest dRequest = (DrugIssueRequest)issuesTable.getValueAt(selectedRow, 5);
        Drug drug = (Drug) issuesTable.getValueAt(selectedRow,1);
        int flag= JOptionPane.showConfirmDialog(this, "Are you sure want to call back the drug?","Warning", JOptionPane.YES_NO_OPTION);
        
        if(flag==0){
        if((dRequest.getCallBackRequest().equals("Yes"))||(dRequest.getStatus().equals("Drug Withdrawn"))){
            JOptionPane.showMessageDialog(null, "Drug already removed from the market!");
            return;
       }else{
            dRequest.setCallBackRequest("Yes");
            dRequest.setStatus("Drug Withdrawn");
            
            for(Drug drug1:ecoSystem.getDrugCatalog().getDrugCatalog()){
                if(drug1.getDrugId() == drug.getDrugId()){
                    drug1.setStatus("Drug Disapproved");
                }
            }
        }
        }
        JOptionPane.showMessageDialog(null, "Drug successfully called back!");
        populateDrugComboBox();
        Drug d = (Drug) drugComboBox.getSelectedItem();
        populateDrugIssueTable(d);
    }//GEN-LAST:event_callBackBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        Drug drug = (Drug) drugComboBox.getSelectedItem();
        if (drug != null) {
            populateDrugIssueTable(drug);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton callBackBtn;
    private javax.swing.JComboBox drugComboBox;
    private javax.swing.JTable issuesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
