/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Medication.Drug;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DrugIssueRequest;
import Business.WorkQueue.DrugReviewRequest;
import Business.WorkQueue.SalesWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ManageMedicineReviewsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicinesReviewJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    
    public ManageMedicineReviewsJPanel(JPanel upc, UserAccount ua, Enterprise ep, EcoSystem es) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.userAccount = ua;
        this.enterprise = ep;
        this.ecoSystem = es;
        
        populateMedicinesReviewTable();
    }

    private void populateMedicinesReviewTable(){
        DefaultTableModel model = (DefaultTableModel) medicineResponseTable.getModel();
        model.setRowCount(0); 
        
        for(WorkRequest request:enterprise.getWorkQueue().getWorkRequestList()){
            if(request instanceof DrugReviewRequest){
                DrugReviewRequest drugReviewRequest = (DrugReviewRequest)request;
               for(Drug drug: drugReviewRequest.getDrugCatalog().getDrugCatalog()){
                    Object[] row = new Object[10];
                    row[0] = drugReviewRequest.getRequestID();
                    row[1] = drug.getDrugName();
                    row[2] = drug;
                    row[3] = drug.getDisease().getDiseaseName();
                    row[4] = drug.getSideEffects();
                    row[5] = drugReviewRequest.getSender().getPerson().getName();
                    row[6] = drug.getPharmaceuticalName();
                    row[7] = drugReviewRequest.getCallBackRequest() == null ? ("No") : (drugReviewRequest.getCallBackRequest());
                    row[8] = drugReviewRequest.getStatus();
                    row[9] = drugReviewRequest;
                    model.addRow(row);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        issueTextArea = new javax.swing.JTextArea();
        sendBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicineResponseTable = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backBtn.setText(">> back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        issueTextArea.setColumns(20);
        issueTextArea.setRows(5);
        jScrollPane2.setViewportView(issueTextArea);

        sendBtn.setBackground(new java.awt.Color(255, 153, 153));
        sendBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sendBtn.setText("Submit");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Review :");

        medicineResponseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Medicine", "Medicine Code", "Disease Cure", "Safety Issues", "Sender", "Pharmaneutical", "Call back", "Status", "Place"
            }
        ));
        jScrollPane1.setViewportView(medicineResponseTable);

        refreshBtn.setBackground(new java.awt.Color(255, 153, 153));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 3, 23)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Manage Medicine Reviews Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(refreshBtn)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendBtn)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(refreshBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backBtn)
                        .addComponent(jLabel3)))
                .addGap(37, 37, 37)
                .addComponent(sendBtn)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        String issue = issueTextArea.getText();

        if((issue.equals(""))||(issue.equals(null))){
            JOptionPane.showMessageDialog(null, "Please fill up the details in the box provided!");
            return;
        }

        int selectedRow = medicineResponseTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to proceed");
            return;
        }
        DrugReviewRequest drr = (DrugReviewRequest) medicineResponseTable.getValueAt(selectedRow, 9);
       // DrugReviewRequest request = new DrugReviewRequest();
        drr.setDrugReviews(issue);
        drr.setStatus("Issue sent");
        drr.setReceiver(userAccount);
        drr.setIsReplied("Yes");
        populateMedicinesReviewTable();
        JOptionPane.showMessageDialog(null, "Request Submitted!");
        resetFields();
        
        
    }//GEN-LAST:event_sendBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        populateMedicinesReviewTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

     private void resetFields(){
         issueTextArea.setText("");
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea issueTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable medicineResponseTable;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
