/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPersonWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    public SalesPersonWorkAreaJPanel(JPanel upc, UserAccount ua, Organization org, Enterprise ep, EcoSystem es) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.enterprise = ep;
        this.ecoSystem = es;
        this.organization = org;
        this.userAccount = ua;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        managePreDrugPatientBTn = new javax.swing.JButton();
        manageMedicineBtn = new javax.swing.JButton();
        manageReviewsBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("SalesPerson Work Area Panel");

        managePreDrugPatientBTn.setBackground(new java.awt.Color(255, 153, 153));
        managePreDrugPatientBTn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        managePreDrugPatientBTn.setText(" Prescribed Medicines Sales Request");
        managePreDrugPatientBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePreDrugPatientBTnActionPerformed(evt);
            }
        });

        manageMedicineBtn.setBackground(new java.awt.Color(255, 153, 153));
        manageMedicineBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageMedicineBtn.setText("Manage Medicines");
        manageMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMedicineBtnActionPerformed(evt);
            }
        });

        manageReviewsBtn.setBackground(new java.awt.Color(255, 153, 153));
        manageReviewsBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageReviewsBtn.setText("Medicines Reviews");
        manageReviewsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageReviewsBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/sale2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(managePreDrugPatientBTn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageMedicineBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageReviewsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel1)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(managePreDrugPatientBTn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageReviewsBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(manageMedicineBtn)))
                .addContainerGap(489, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managePreDrugPatientBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePreDrugPatientBTnActionPerformed
        ManagePrescribedDrugJPanel panel = new ManagePrescribedDrugJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("ManagePrescribedDrugJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePreDrugPatientBTnActionPerformed

    private void manageMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMedicineBtnActionPerformed
        ManageMedicinesJPanel panel = new ManageMedicinesJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("ManageMedicinesJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMedicineBtnActionPerformed

    private void manageReviewsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageReviewsBtnActionPerformed
        ManageMedicineReviewsJPanel panel = new ManageMedicineReviewsJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("ManageMedicineReviewsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageReviewsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageMedicineBtn;
    private javax.swing.JButton managePreDrugPatientBTn;
    private javax.swing.JButton manageReviewsBtn;
    // End of variables declaration//GEN-END:variables
}
