/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
            
    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        
        populateNetworkComboBox();
    }
    
       private void populateNetworkComboBox() {
        networkComboBox.removeAllItems();

        for (Network network : ecoSystem.getNetworkList()) {
            networkComboBox.addItem(network);
            populateEnterpriseTable(network);
        }
    }
    
    private void populateEnterpriseTable(Network network){
        DefaultTableModel model = (DefaultTableModel) enterpriseTable.getModel();
        model.setRowCount(0);
        
            if((network!=null)&&(network.getEnterpriseDirectory() != null)){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                Object row[] = new Object[4];
                row[0] = enterprise.getEnterpriseId();
                row[1] = enterprise.getEnterpriseType().getValue();
                row[2] = enterprise;
                row[3] = enterprise.getAddress().getCity();
                model.addRow(row);
            }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        backBtn = new javax.swing.JButton();
        updateEnterpriseBtn = new javax.swing.JButton();
        deleteEnterpriseBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        createEnterpriseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Enterprise Panel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Network :");

        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backBtn.setText(">> Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        updateEnterpriseBtn.setBackground(new java.awt.Color(255, 153, 153));
        updateEnterpriseBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updateEnterpriseBtn.setText("Update Enterprise");
        updateEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEnterpriseBtnActionPerformed(evt);
            }
        });

        deleteEnterpriseBtn.setBackground(new java.awt.Color(255, 153, 153));
        deleteEnterpriseBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deleteEnterpriseBtn.setText("Delete Enterprise");
        deleteEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEnterpriseBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(255, 153, 153));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        createEnterpriseBtn.setBackground(new java.awt.Color(255, 153, 153));
        createEnterpriseBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        createEnterpriseBtn.setText("Create Enterprise");
        createEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseBtnActionPerformed(evt);
            }
        });

        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise ID", "Enterprise Type", "Name", "Place"
            }
        ));
        jScrollPane1.setViewportView(enterpriseTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(backBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(57, 57, 57)
                                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(updateEnterpriseBtn)
                                    .addGap(34, 34, 34)
                                    .addComponent(deleteEnterpriseBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(createEnterpriseBtn))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(refreshBtn)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(refreshBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateEnterpriseBtn)
                    .addComponent(deleteEnterpriseBtn)
                    .addComponent(createEnterpriseBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEnterpriseBtnActionPerformed
        
        int selectedRow = enterpriseTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to delete!");
            return;
        }
        int enterpriseId  = (Integer)enterpriseTable.getValueAt(selectedRow,0);
        
        Network network = (Network)networkComboBox.getSelectedItem();
        //Enterprise enterprise = enterpriseTable.get
        
        int flag= JOptionPane.showConfirmDialog(this, "Are you sure want to remove?","Warning", JOptionPane.YES_NO_OPTION);
        
        if(flag==0){
            Enterprise enterprise = network.getEnterpriseDirectory().searchEnterprise(enterpriseId);
            if(enterprise!=null){
            network.getEnterpriseDirectory().getEnterpriseList().remove(enterprise);
          }
        }
        network = (Network) networkComboBox.getSelectedItem();
        populateEnterpriseTable(network);
    }//GEN-LAST:event_deleteEnterpriseBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        Network network = (Network) networkComboBox.getSelectedItem();
        populateEnterpriseTable(network);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void createEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseBtnActionPerformed
       CreateEnterpriseJPanel panel = new CreateEnterpriseJPanel(userProcessContainer, ecoSystem);
       userProcessContainer.add("CreateEnterpriseJPanel", panel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_createEnterpriseBtnActionPerformed

    private void updateEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEnterpriseBtnActionPerformed
        int selectedRow = enterpriseTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to update!");
            return;
        }
        int enterpriseId  = (Integer)enterpriseTable.getValueAt(selectedRow,0);
        
        Network network = (Network)networkComboBox.getSelectedItem();
        Enterprise enterprise = network.getEnterpriseDirectory().searchEnterprise(enterpriseId);
      //  Enterprise enterprise  = (Enterprise) enterpriseTable.getValueAt(selectedRow, 0);
        if(enterprise!=null){
        UpdateEnterpriseJPanel panel = new UpdateEnterpriseJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("UpdateEnterpriseJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_updateEnterpriseBtnActionPerformed

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed
       Network network = (Network) networkComboBox.getSelectedItem();
       populateEnterpriseTable(network);
    }//GEN-LAST:event_networkComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createEnterpriseBtn;
    private javax.swing.JButton deleteEnterpriseBtn;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton updateEnterpriseBtn;
    // End of variables declaration//GEN-END:variables
}
