/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.HealthOfficialAuthority.HOAuthority;
import Business.Network.Network;
import Business.Organization.Organization;
import UserInterface.ManageHealthOfficialAuthority.ManageHealthOfficialAuthorityJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author PC
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    public SystemAdminWorkAreaJPanel(JPanel upc, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.ecoSystem = system;
        populateSystemJTree();
    }

    public void populateSystemJTree(){
        DefaultTreeModel model = (DefaultTreeModel) systemJTree.getModel();
        
        ArrayList<Network> networkList = ecoSystem.getNetworkList();
        HOAuthority authority = ecoSystem.getAuthority();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        Network network;
        Enterprise enterprise;
        Organization organization;
        
        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("States");
        DefaultMutableTreeNode authorities = new DefaultMutableTreeNode("Authority");
        DefaultMutableTreeNode roots = (DefaultMutableTreeNode) model.getRoot();
        roots.removeAllChildren();
        roots.insert(networks, 0);
        roots.insert(authorities,0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode authorityNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        authorityNode = new DefaultMutableTreeNode(authority.getName());
        authorities.insert(authorityNode,0);
        
        for(int i=0; i<networkList.size(); i++){
            network = networkList.get(i);
            networkNode = new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);
            
            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            
            for(int j=0;j<enterpriseList.size();j++){
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);
                
                organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                
                for (int k = 0; k < organizationList.size(); k++) {
                    organization = organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
            
        }
        model.reload();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        systemJTree = new javax.swing.JTree();
        systemAdminWorkAreaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manageNetworkBtn = new javax.swing.JButton();
        manageEnterpriseBtn = new javax.swing.JButton();
        manageEnterpriseAdminBtn = new javax.swing.JButton();
        manageAuthorityBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1324, 1078));
        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        systemJTree.setBackground(new java.awt.Color(255, 204, 204));
        systemJTree.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("USA");
        systemJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        systemJTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                systemJTreeValueChanged(evt);
            }
        });
        systemJTree.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                systemJTreePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(systemJTree);

        jPanel1.add(jScrollPane1);

        jSplitPane1.setLeftComponent(jPanel1);

        systemAdminWorkAreaPanel.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SYSTEM ADMIN WORK AREA PANEL");

        manageNetworkBtn.setBackground(new java.awt.Color(255, 102, 102));
        manageNetworkBtn.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        manageNetworkBtn.setText(" Network");
        manageNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkBtnActionPerformed(evt);
            }
        });

        manageEnterpriseBtn.setBackground(new java.awt.Color(255, 102, 102));
        manageEnterpriseBtn.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        manageEnterpriseBtn.setText("Enterprise");
        manageEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseBtnActionPerformed(evt);
            }
        });

        manageEnterpriseAdminBtn.setBackground(new java.awt.Color(255, 102, 102));
        manageEnterpriseAdminBtn.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        manageEnterpriseAdminBtn.setText("Enterprise Admin");
        manageEnterpriseAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminBtnActionPerformed(evt);
            }
        });

        manageAuthorityBtn.setBackground(new java.awt.Color(255, 102, 102));
        manageAuthorityBtn.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        manageAuthorityBtn.setText("Health Official Authority");
        manageAuthorityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAuthorityBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout systemAdminWorkAreaPanelLayout = new javax.swing.GroupLayout(systemAdminWorkAreaPanel);
        systemAdminWorkAreaPanel.setLayout(systemAdminWorkAreaPanelLayout);
        systemAdminWorkAreaPanelLayout.setHorizontalGroup(
            systemAdminWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminWorkAreaPanelLayout.createSequentialGroup()
                .addGroup(systemAdminWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(systemAdminWorkAreaPanelLayout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addGroup(systemAdminWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(manageAuthorityBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageEnterpriseAdminBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageEnterpriseBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageNetworkBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(systemAdminWorkAreaPanelLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1)))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        systemAdminWorkAreaPanelLayout.setVerticalGroup(
            systemAdminWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminWorkAreaPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(130, 130, 130)
                .addComponent(manageNetworkBtn)
                .addGap(54, 54, 54)
                .addComponent(manageEnterpriseBtn)
                .addGap(66, 66, 66)
                .addComponent(manageEnterpriseAdminBtn)
                .addGap(82, 82, 82)
                .addComponent(manageAuthorityBtn)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(systemAdminWorkAreaPanel);

        add(jSplitPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void systemJTreePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_systemJTreePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_systemJTreePropertyChange

    private void manageNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkBtnActionPerformed
        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add("ManageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkBtnActionPerformed

    private void manageEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseBtnActionPerformed
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add("ManageEnterpriseJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseBtnActionPerformed

    private void manageEnterpriseAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminBtnActionPerformed
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseAdminBtnActionPerformed

    private void manageAuthorityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAuthorityBtnActionPerformed
        ManageHealthOfficialAuthorityJPanel manageAuthorityAdminJPanel = new ManageHealthOfficialAuthorityJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add("ManageHealthOfficialAuthorityJPanel", manageAuthorityAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAuthorityBtnActionPerformed

    private void systemJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_systemJTreeValueChanged
         
    }//GEN-LAST:event_systemJTreeValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageAuthorityBtn;
    private javax.swing.JButton manageEnterpriseAdminBtn;
    private javax.swing.JButton manageEnterpriseBtn;
    private javax.swing.JButton manageNetworkBtn;
    private javax.swing.JPanel systemAdminWorkAreaPanel;
    private javax.swing.JTree systemJTree;
    // End of variables declaration//GEN-END:variables
}
